<?php

namespace Deployer;

desc('Install PHP with common extensions');
task('provision:php', function () {
    $version = get('php_version', '8.4');

    info("Installing PHP {$version}...");

    sudo('apt-get update');
    sudo('apt-get install -y software-properties-common');
    sudo('add-apt-repository -y ppa:ondrej/php');
    sudo('apt-get update');

    $extensions = [
        'fpm', 'cli', 'pgsql', 'mbstring', 'xml', 'curl',
        'zip', 'gd', 'redis', 'bcmath', 'intl', 'opcache', 'readline',
    ];

    $packages = array_map(fn ($ext) => "php{$version}-{$ext}", $extensions);
    sudo('apt-get install -y ' . implode(' ', $packages));

    sudo("systemctl enable php{$version}-fpm");
    sudo("systemctl start php{$version}-fpm");

    $phpVersion = run('php -v | head -1');
    info("PHP installed: {$phpVersion}");
});

after('provision:php', 'php:opcache');

desc('Show installed PHP version and extensions');
task('php:info', function () {
    $version = run('php -v | head -1');
    writeln($version);
    writeln('');
    writeln('Loaded extensions:');
    $extensions = run('php -m');
    writeln($extensions);
});

desc('Configure OPcache for production');
task('php:opcache', function () {
    $version = get('php_version', '8.4');
    $configPath = "/etc/php/{$version}/mods-available/opcache.ini";

    // Production-optimized OPcache settings for Laravel
    $config = <<<'INI'
; OPcache settings optimized for Laravel production
zend_extension=opcache.so
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=256
opcache.interned_strings_buffer=64
opcache.max_accelerated_files=30000
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.save_comments=1
opcache.fast_shutdown=1
INI;

    sudo("tee {$configPath} > /dev/null << 'EOF'\n{$config}\nEOF");
    sudo("systemctl restart php{$version}-fpm");

    info("OPcache configured for production (validate_timestamps=0)");
    info("Note: PHP-FPM restart is required after each deploy to load new code");
});

desc('Show OPcache status');
task('php:opcache:status', function () {
    $status = run("php -r \"var_export(opcache_get_status(false));\" 2>/dev/null || echo 'OPcache not available'");
    writeln($status);
});

// PHP-FPM configuration defaults (can be overridden in deploy.php)
set('php_upload_max_filesize', '128M');
set('php_post_max_size', '128M');
set('php_max_execution_time', '300');
set('php_memory_limit', '256M');

desc('Configure PHP-FPM settings for Laravel (uploads, memory, execution time)');
task('php:fpm-config', function () {
    $version = get('php_version', '8.4');
    $configPath = "/etc/php/{$version}/fpm/conf.d/99-laravel.ini";

    $uploadMax = get('php_upload_max_filesize');
    $postMax = get('php_post_max_size');
    $maxExec = get('php_max_execution_time');
    $memLimit = get('php_memory_limit');

    $config = <<<INI
; Laravel-optimized PHP-FPM settings
; Generated by deployer-laravel-stack

; File uploads (128MB default for large PDFs, media files)
upload_max_filesize = {$uploadMax}
post_max_size = {$postMax}

; Execution limits
max_execution_time = {$maxExec}
memory_limit = {$memLimit}

; Security
expose_php = Off
INI;

    sudo("tee {$configPath} > /dev/null << 'EOF'\n{$config}\nEOF");
    sudo("systemctl restart php{$version}-fpm");

    info("PHP-FPM configured: upload={$uploadMax}, post={$postMax}, memory={$memLimit}");
});

// Run FPM config after OPcache during provisioning
after('php:opcache', 'php:fpm-config');

desc('Configure PHP-FPM pool with explicit user/group settings');
task('php:fpm-pool', function () {
    $version = get('php_version', '8.4');
    $poolPath = "/etc/php/{$version}/fpm/pool.d/www.conf";

    info('Configuring PHP-FPM pool...');

    // Create explicit pool configuration
    $config = <<<'INI'
[www]
; User/Group configuration
user = www-data
group = www-data

; Socket configuration
listen = /var/run/php/php{VERSION}-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

; Process manager settings
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
pm.max_requests = 500

; Error logging
php_admin_flag[log_errors] = on
php_admin_value[error_log] = /var/log/php-fpm/www-error.log

; Security
security.limit_extensions = .php
INI;

    // Replace {VERSION} placeholder
    $config = str_replace('{VERSION}', $version, $config);

    // Create log directory
    sudo('mkdir -p /var/log/php-fpm');
    sudo('chown www-data:www-data /var/log/php-fpm');

    // Write pool configuration
    sudo("tee {$poolPath} > /dev/null << 'EOF'\n{$config}\nEOF");
    sudo("systemctl restart php{$version}-fpm");

    info('PHP-FPM pool configured with www-data user/group');
});

desc('Show PHP-FPM pool status');
task('php:fpm-pool:status', function () {
    $version = get('php_version', '8.4');

    // Check pool process
    $processes = run("ps aux | grep 'php-fpm.*pool www' | grep -v grep || echo 'No pool processes found'");
    writeln($processes);

    // Check socket
    $socket = run("ls -la /var/run/php/php{$version}-fpm.sock 2>/dev/null || echo 'Socket not found'");
    writeln($socket);
});
