<?php

namespace Deployer;

/**
 * Generate deploy.php based on user configuration.
 *
 * @param array<string, mixed> $config
 */
function generateDeployPhp(array $config): string
{
    $appName = $config['app_name'];
    $repository = $config['repository'];
    $serverHostname = $config['server_hostname'];
    $prodDomain = $config['prod_domain'];
    $hasStaging = $config['has_staging'];
    $stagingDomain = $config['staging_domain'];
    $database = $config['database'];
    $queue = $config['queue'];
    $webServer = $config['web_server'];
    $secretsMode = $config['secrets_mode'];

    // App slug for paths
    $appSlug = strtolower(preg_replace('/[^a-zA-Z0-9]/', '', $appName));

    // Build secrets array based on database
    $requiredSecrets = "['DEPLOYER_SUDO_PASS', 'DEPLOYER_APP_KEY']";
    if ($database !== 'sqlite') {
        $requiredSecrets = "['DEPLOYER_SUDO_PASS', 'DEPLOYER_DB_PASSWORD', 'DEPLOYER_APP_KEY']";
    }

    // Database configuration section
    $dbConfig = match ($database) {
        'sqlite' => <<<'PHP'

// SQLite configuration
set('db_connection', 'sqlite');

// Add database directory to shared directories
add('shared_dirs', ['database']);
add('writable_dirs', ['database']);
PHP,
        'mysql' => <<<'PHP'

// MySQL configuration
set('db_connection', 'mysql');
PHP,
        default => <<<'PHP'

// PostgreSQL configuration (default)
set('db_connection', 'pgsql');
PHP,
    };

    // Queue configuration
    $queueConfig = match ($queue) {
        'none' => "set('queue_connection', 'sync');",
        'database' => "set('queue_connection', 'database');",
        default => "set('queue_connection', 'redis');",
    };

    // Web server configuration
    $webServerConfig = '';
    if ($webServer === 'octane') {
        if ($hasStaging) {
            // Multi-environment: use unique ports per environment to avoid conflicts
            $webServerConfig = <<<'PHP'

// Laravel Octane with FrankenPHP
set('web_server', 'octane');

// Unique ports per environment (avoids FrankenPHP/Caddy admin port conflicts)
set('octane_port', fn () => getStage() === 'prod' ? 8000 : 8001);
set('octane_admin_port', fn () => getStage() === 'prod' ? 2020 : 2021);
PHP;
        } else {
            // Single environment: simple static ports
            $webServerConfig = <<<'PHP'

// Laravel Octane with FrankenPHP
set('web_server', 'octane');
set('octane_port', 8000);
set('octane_admin_port', 2020);
PHP;
        }
    }

    // Staging environment
    $stagingSection = '';
    if ($hasStaging) {
        $stagingSection = <<<PHP

environment('staging', [
    'deploy_path' => '/home/deployer/{$appSlug}-staging',
    'domain' => '{$stagingDomain}',
    'db_name' => '{$appSlug}_staging',
    'redis_db' => 1,
    'app_debug' => true,
    'log_level' => 'debug',
]);
PHP;
    }

    // SQLite shared_env additions
    $sqliteEnvNote = '';
    if ($database === 'sqlite') {
        $sqliteEnvNote = <<<'PHP'

    // SQLite database path (absolute path required)
    'DB_DATABASE' => '{{deploy_path}}/shared/database/database.sqlite',
PHP;
    }

    // Version stamp
    $version = date('Y-m-d H:i:s');

    return <<<PHP
<?php
// Generated by deployer-laravel-stack init wizard
// {$version}

namespace Deployer;

require 'recipe/laravel.php';
require 'vendor/cothinking-dev/deployer-laravel-stack/src/recipe.php';

// ─────────────────────────────────────────────────────────────────────────────
// Application
// ─────────────────────────────────────────────────────────────────────────────

set('application', '{$appName}');
set('repository', '{$repository}');
set('keep_releases', 5);

// ─────────────────────────────────────────────────────────────────────────────
// Server
// ─────────────────────────────────────────────────────────────────────────────

set('server_hostname', getenv('DEPLOYER_HOST') ?: '{$serverHostname}');

host('server')
    ->setHostname(get('server_hostname'))
    ->set('remote_user', 'root')
    ->set('labels', ['stage' => 'server'])
    ->set('deploy_path', '/home/deployer/{$appSlug}');

// ─────────────────────────────────────────────────────────────────────────────
// Database Configuration
// ─────────────────────────────────────────────────────────────────────────────
{$dbConfig}

// ─────────────────────────────────────────────────────────────────────────────
// Queue Configuration
// ─────────────────────────────────────────────────────────────────────────────

{$queueConfig}
{$webServerConfig}

// ─────────────────────────────────────────────────────────────────────────────
// Secrets (from environment)
// ─────────────────────────────────────────────────────────────────────────────

set('secrets', fn () => requireSecrets(
    required: {$requiredSecrets},
    optional: []
));

// ─────────────────────────────────────────────────────────────────────────────
// Environments
// ─────────────────────────────────────────────────────────────────────────────

environment('prod', [
    'deploy_path' => '/home/deployer/{$appSlug}',
    'domain' => '{$prodDomain}',
    'db_name' => '{$appSlug}',
    'redis_db' => 0,
]);
{$stagingSection}

// ─────────────────────────────────────────────────────────────────────────────
// Shared Environment Variables
// ─────────────────────────────────────────────────────────────────────────────

set('shared_env', [
    // Filesystem
    'FILESYSTEM_DISK' => 'local',

    // Mail
    'MAIL_MAILER' => 'smtp',
    'MAIL_FROM_ADDRESS' => 'hello@{$prodDomain}',
    'MAIL_FROM_NAME' => '\${APP_NAME}',
{$sqliteEnvNote}
]);

// ─────────────────────────────────────────────────────────────────────────────
// Hooks
// ─────────────────────────────────────────────────────────────────────────────

after('deploy:failed', 'deploy:unlock');

PHP;
}

/**
 * Generate deploy/dep wrapper script.
 */
function generateDepWrapper(string $secretsMode): string
{
    $version = date('Y-m-d H:i:s');

    return <<<'BASH'
#!/bin/bash
# Deployer wrapper with secrets management
# Generated by deployer-laravel-stack init wizard
# BASH . $version

set -eo pipefail

# ─────────────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────────────

# Find project root (works from any subdirectory)
find_project_root() {
    local dir="$PWD"
    while [[ "$dir" != "/" ]]; do
        if [[ -f "$dir/deploy.php" && -f "$dir/composer.json" ]]; then
            echo "$dir"
            return 0
        fi
        dir="$(dirname "$dir")"
    done
    return 1
}

PROJECT_DIR="$(find_project_root)" || {
    echo "Error: Could not find project root (looking for deploy.php)" >&2
    exit 1
}

cd "$PROJECT_DIR"

readonly ENVIRONMENTS="${DEPLOYER_ENVIRONMENTS:-prod staging server}"
readonly PROD_ENVS="${DEPLOYER_PROD_ENVIRONMENTS:-prod staging}"
readonly APP_NAME="${DEPLOYER_APP_NAME:-Application}"

# ─────────────────────────────────────────────────────────────────────────────
# Colors (with fallback for non-interactive terminals)
# ─────────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && [[ "${TERM:-}" != "dumb" ]]; then
    readonly RED='\033[0;31m'
    readonly GREEN='\033[0;32m'
    readonly BLUE='\033[0;34m'
    readonly YELLOW='\033[0;33m'
    readonly NC='\033[0m'
else
    readonly RED='' GREEN='' BLUE='' YELLOW='' NC=''
fi

error() { echo -e "${RED}Error: $*${NC}" >&2; exit 1; }
info() { echo -e "${BLUE}$*${NC}"; }
success() { echo -e "${GREEN}$*${NC}"; }
warn() { echo -e "${YELLOW}$*${NC}"; }

# ─────────────────────────────────────────────────────────────────────────────
# Usage
# ─────────────────────────────────────────────────────────────────────────────

show_usage() {
    cat <<EOF
Usage: dep <command> <environment>

Environments:
  prod     - Production
  staging  - Staging
  server   - Bootstrap (runs as root)

Fresh server setup:
  dep setup:server server && dep setup:environment prod

Regular deploys:
  dep deploy prod
  dep deploy staging

Multi-environment commands:
  dep caddy:all     - Configure Caddy for all environments
  dep deploy:all    - Deploy to all environments
EOF
    exit 1
}

# ─────────────────────────────────────────────────────────────────────────────
# Detect Secrets Mode
# ─────────────────────────────────────────────────────────────────────────────

SECRETS_MODE=""
SECRETS_FILE=""

if [[ -f "deploy/secrets.tpl" && -f "deploy/secrets.env" ]]; then
    error "Both deploy/secrets.tpl and deploy/secrets.env exist.\nRemove one to resolve the conflict."
elif [[ -f "deploy/secrets.tpl" ]]; then
    SECRETS_MODE="1password"
    SECRETS_FILE="deploy/secrets.tpl"
elif [[ -f "deploy/secrets.env" ]]; then
    SECRETS_MODE="env"
    SECRETS_FILE="deploy/secrets.env"
else
    error "No secrets file found.\nCreate deploy/secrets.tpl (for 1Password) or deploy/secrets.env (for plain .env).\nRun 'vendor/bin/dep init' to set up your project."
fi

# ─────────────────────────────────────────────────────────────────────────────
# Parse Arguments
# ─────────────────────────────────────────────────────────────────────────────

ENV=""
COMMAND=""
ARGS=()

for arg in "$@"; do
    for env in $ENVIRONMENTS; do
        if [[ "$arg" == "$env" ]]; then
            ENV="$arg"
            break
        fi
    done
    if [[ -z "$COMMAND" && "$arg" != -* ]]; then
        COMMAND="$arg"
    fi
    ARGS+=("$arg")
done

# Handle multi-environment commands
if [[ "$COMMAND" == "caddy:all" || "$COMMAND" == "deploy:all" ]]; then
    ENV="all"
fi

[[ -z "$ENV" ]] && show_usage

# ─────────────────────────────────────────────────────────────────────────────
# Validate Prerequisites
# ─────────────────────────────────────────────────────────────────────────────

[[ -f "vendor/bin/dep" ]] || error "Deployer not installed. Run: composer install"

if [[ "$SECRETS_MODE" == "1password" ]]; then
    command -v op >/dev/null 2>&1 || error "1Password CLI (op) not installed.\nInstall: brew install 1password-cli"
fi

# GitHub CLI is optional - warn but don't fail
if ! command -v gh >/dev/null 2>&1; then
    warn "GitHub CLI (gh) not installed. Some features may not work."
    warn "Install with: brew install gh"
fi

# ─────────────────────────────────────────────────────────────────────────────
# Authenticate
# ─────────────────────────────────────────────────────────────────────────────

if [[ "$SECRETS_MODE" == "1password" ]]; then
    if ! op account list &>/dev/null 2>&1; then
        info "Signing in to 1Password..."
        eval "$(op signin)"
    fi
fi

if command -v gh >/dev/null 2>&1; then
    if ! gh auth status &>/dev/null 2>&1; then
        info "Authenticating with GitHub..."
        gh auth login
    fi
fi

# ─────────────────────────────────────────────────────────────────────────────
# Set Environment
# ─────────────────────────────────────────────────────────────────────────────

DEPLOYER_ENV="$ENV"
[[ "$ENV" == "server" || "$ENV" == "all" ]] && DEPLOYER_ENV="prod"

export DEPLOYER_ENV
info "Environment: $DEPLOYER_ENV"
info "Secrets mode: $SECRETS_MODE"

# ─────────────────────────────────────────────────────────────────────────────
# Run Deployer
# ─────────────────────────────────────────────────────────────────────────────

run_deployer() {
    if [[ "$SECRETS_MODE" == "1password" ]]; then
        op run --cache=false --env-file="$SECRETS_FILE" -- vendor/bin/dep "$@"
    else
        # Source env file and run deployer
        set -a
        source "$SECRETS_FILE"
        set +a
        vendor/bin/dep "$@"
    fi
}

case "$COMMAND" in
    caddy:all)
        i=1
        total=$(echo $PROD_ENVS | wc -w | tr -d ' ')
        for env in $PROD_ENVS; do
            success "[$i/$total] Configuring Caddy for $env..."
            run_deployer caddy:configure "$env" -v
            echo ""
            ((i++))
        done
        success "Caddy configured for all environments"
        ;;
    deploy:all)
        i=1
        total=$(echo $PROD_ENVS | wc -w | tr -d ' ')
        for env in $PROD_ENVS; do
            success "[$i/$total] Deploying $env..."
            run_deployer deploy "$env" -v
            echo ""
            ((i++))
        done
        success "Deployed to all environments"
        ;;
    *)
        run_deployer "${ARGS[@]}"
        ;;
esac
BASH;
}

/**
 * Generate deploy/secrets.tpl for 1Password mode.
 *
 * @param array<string, mixed> $config
 */
function generateSecretsTpl(array $config): string
{
    $vault = $config['op_vault'];
    $item = $config['op_item'];
    $database = $config['database'];

    $dbPassword = '';
    if ($database !== 'sqlite') {
        $dbPassword = "DEPLOYER_DB_PASSWORD=op://{$vault}/{$item}/db-password";
    }

    $version = date('Y-m-d H:i:s');

    return <<<TPL
# Secrets template for 1Password CLI
# Generated by deployer-laravel-stack init wizard
# {$version}
#
# Create a 1Password item in vault "{$vault}" named "{$item}"
# with these fields:
#   - sudo-password
#   - db-password (if not using SQLite)
#   - prod-app-key (generate with: php artisan key:generate --show)
#   - staging-app-key (if using staging environment)
#
# Usage: ./deploy/dep <command> <environment>

DEPLOYER_SUDO_PASS=op://{$vault}/{$item}/sudo-password
{$dbPassword}
DEPLOYER_APP_KEY=op://{$vault}/{$item}/\$DEPLOYER_ENV-app-key

# Optional secrets (add more as needed)
# DEPLOYER_MAIL_PASSWORD=op://{$vault}/{$item}/mail-password
# DEPLOYER_AWS_SECRET=op://{$vault}/{$item}/aws-secret

TPL;
}

/**
 * Generate deploy/secrets.env for plain env mode.
 *
 * @param array<string, mixed> $config
 */
function generateSecretsEnv(array $config): string
{
    $database = $config['database'];

    $dbPassword = '';
    if ($database !== 'sqlite') {
        $dbPassword = "DEPLOYER_DB_PASSWORD=your-database-password-here";
    }

    $version = date('Y-m-d H:i:s');

    return <<<ENV
# Deployment secrets (plain .env mode)
# Generated by deployer-laravel-stack init wizard
# {$version}
#
# ⚠ WARNING: This file contains sensitive data.
# - NEVER commit to version control
# - Ensure this file is in .gitignore
# - Replace all placeholder values before deploying
#
# Usage: ./deploy/dep <command> <environment>

# Required secrets
DEPLOYER_SUDO_PASS=your-sudo-password-here
{$dbPassword}
DEPLOYER_APP_KEY=base64:your-app-key-here

# Generate APP_KEY with: php artisan key:generate --show

# Optional secrets (add more as needed)
# DEPLOYER_MAIL_PASSWORD=
# DEPLOYER_AWS_SECRET=

ENV;
}

/**
 * Generate deploy/secrets.env.example for GitHub Actions mode.
 *
 * @param array<string, mixed> $config
 */
function generateSecretsEnvExample(array $config): string
{
    $database = $config['database'];

    $dbPasswordLine = '';
    $dbPasswordGh = '';
    if ($database !== 'sqlite') {
        $dbPasswordLine = "DEPLOYER_DB_PASSWORD=      # Database password";
        $dbPasswordGh = <<<'GH'

# Database password
gh secret set DEPLOYER_DB_PASSWORD --env staging
gh secret set DEPLOYER_DB_PASSWORD --env production
GH;
    }

    $version = date('Y-m-d H:i:s');

    return <<<ENV
# GitHub Actions Secrets Reference
# Generated by deployer-laravel-stack init wizard
# {$version}
#
# This file documents the secrets required for GitHub Actions CI/CD.
# These should be set in GitHub Repository Settings → Secrets and variables → Actions
#
# Set secrets for each environment (staging, production):
#   gh secret set SECRET_NAME --env environment_name
#
# ─────────────────────────────────────────────────────────────────────────────
# REQUIRED SECRETS
# ─────────────────────────────────────────────────────────────────────────────

SSH_PRIVATE_KEY=           # Private key from 'dep github:ci-key server'
DEPLOYER_SUDO_PASS=        # Server sudo password for deployer user
DEPLOYER_APP_KEY=          # Laravel APP_KEY (different for each environment!)
{$dbPasswordLine}

# ─────────────────────────────────────────────────────────────────────────────
# OPTIONAL SECRETS (add as needed)
# ─────────────────────────────────────────────────────────────────────────────

# DEPLOYER_MAILGUN_SECRET=   # Mailgun API secret
# DEPLOYER_LOOPS_API_KEY=    # Loops.so API key
# DEPLOYER_TURNSTILE_SECRET= # Cloudflare Turnstile secret
# DEPLOYER_STRIPE_SECRET=    # Stripe API secret
# DEPLOYER_AWS_SECRET=       # AWS secret access key

# ─────────────────────────────────────────────────────────────────────────────
# HOW TO SET SECRETS
# ─────────────────────────────────────────────────────────────────────────────
#
# 1. Generate CI/CD SSH key:
#    ./deploy/dep github:ci-key server
#
# 2. Save the private key to a file (e.g., /tmp/ci_key)
#
# 3. Set secrets using GitHub CLI:
#
# SSH key (from github:ci-key output)
gh secret set SSH_PRIVATE_KEY --env staging < /tmp/ci_key
gh secret set SSH_PRIVATE_KEY --env production < /tmp/ci_key

# Sudo password
gh secret set DEPLOYER_SUDO_PASS --env staging
gh secret set DEPLOYER_SUDO_PASS --env production

# App keys (generate separate keys for each environment!)
# php artisan key:generate --show
gh secret set DEPLOYER_APP_KEY --env staging
gh secret set DEPLOYER_APP_KEY --env production
{$dbPasswordGh}

# 4. Clean up the temporary key file:
#    rm /tmp/ci_key

ENV;
}

/**
 * Generate .github/workflows/deploy.yml for GitHub Actions CI/CD.
 *
 * @param array<string, mixed> $config
 */
function generateGitHubActionsWorkflow(array $config): string
{
    $hasStaging = $config['has_staging'];
    $database = $config['database'];

    // Build optional secrets list
    $optionalSecrets = [];
    if ($database !== 'sqlite') {
        $optionalSecrets[] = 'DEPLOYER_DB_PASSWORD: ${{ secrets.DEPLOYER_DB_PASSWORD }}';
    }
    $optionalSecretsYaml = implode("\n          ", $optionalSecrets);
    if (! empty($optionalSecretsYaml)) {
        $optionalSecretsYaml = "\n          " . $optionalSecretsYaml;
    }

    // Staging job (only if staging is enabled)
    $stagingJob = '';
    if ($hasStaging) {
        $stagingJob = <<<YAML

  # ─────────────────────────────────────────────────────────────────────────────
  # Deploy to Staging
  # ─────────────────────────────────────────────────────────────────────────────
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Deploy to staging
        uses: deployphp/action@v1
        with:
          private-key: \${{ secrets.SSH_PRIVATE_KEY }}
          dep: deploy staging -v
        env:
          DEPLOYER_SUDO_PASS: \${{ secrets.DEPLOYER_SUDO_PASS }}
          DEPLOYER_APP_KEY: \${{ secrets.DEPLOYER_APP_KEY }}{$optionalSecretsYaml}
YAML;
    }

    // Workflow dispatch options
    $workflowDispatch = $hasStaging ? <<<YAML
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
YAML : <<<YAML
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'production'
        type: choice
        options:
          - production
YAML;

    // Concurrency group
    $concurrencyGroup = $hasStaging
        ? "deploy-\${{ github.ref_name == 'main' && 'production' || github.ref_name == 'develop' && 'staging' || github.event.inputs.environment }}"
        : "deploy-production";

    // Branch triggers
    $branchTriggers = $hasStaging ? <<<YAML
      - main
      - develop
YAML : <<<YAML
      - main
YAML;

    // Production job condition
    $prodCondition = $hasStaging
        ? "github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')"
        : "github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'";

    $version = date('Y-m-d H:i:s');

    return <<<YAML
# GitHub Actions CI/CD workflow for Laravel with deployer-laravel-stack
# Generated by deployer-laravel-stack init wizard
# {$version}
#
# Branch workflow:
#   - Push to 'main'    -> Deploy to production
#   - Push to 'develop' -> Deploy to staging (if enabled)
#   - Manual trigger    -> Choose environment via workflow_dispatch
#
# Required GitHub Secrets (per environment):
#   - SSH_PRIVATE_KEY: Private key from 'dep github:ci-key server'
#   - DEPLOYER_SUDO_PASS: Server sudo password
#   - DEPLOYER_APP_KEY: Laravel APP_KEY (different per environment!)

name: Deploy

on:
  push:
    branches:
{$branchTriggers}
{$workflowDispatch}

# Prevent concurrent deploys to the same environment
concurrency:
  group: {$concurrencyGroup}
  cancel-in-progress: false

jobs:
  # ─────────────────────────────────────────────────────────────────────────────
  # Test Job - Required before deployment
  # ─────────────────────────────────────────────────────────────────────────────
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=\$(composer config cache-files-dir)" >> \$GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: \${{ steps.composer-cache.outputs.dir }}
          key: \${{ runner.os }}-composer-\${{ hashFiles('**/composer.lock') }}
          restore-keys: \${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Create test database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Laravel Pint
        run: vendor/bin/pint --test

      - name: Run Larastan (if configured)
        run: |
          if [ -f phpstan.neon ] || [ -f phpstan.neon.dist ]; then
            vendor/bin/phpstan analyse --memory-limit=2G
          else
            echo "Skipping Larastan - no phpstan.neon found"
          fi

      - name: Run PHPUnit tests
        run: php artisan test
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
{$stagingJob}

  # ─────────────────────────────────────────────────────────────────────────────
  # Deploy to Production
  # ─────────────────────────────────────────────────────────────────────────────
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: {$prodCondition}
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Deploy to production
        uses: deployphp/action@v1
        with:
          private-key: \${{ secrets.SSH_PRIVATE_KEY }}
          dep: deploy prod -v
        env:
          DEPLOYER_SUDO_PASS: \${{ secrets.DEPLOYER_SUDO_PASS }}
          DEPLOYER_APP_KEY: \${{ secrets.DEPLOYER_APP_KEY }}{$optionalSecretsYaml}
YAML;
}
